baseURL: 'https://aicube.fun/'
languageCode: 'en-us'
title: 'AICube.FUN'
theme: 'financlub'
googleAnalytics: 'G-D6W5L8YCC4'
hasCJKLanguage: true
summaryLength: 42
taxonomies:
  tags: 'tags'
  category: 'category'
  social: 'social'
  author: 'author'
params:
  catesytles:
    Marketing: is-warning
    Efficiency: is-info
    Technology: is-success
    Thoughts: is-primary
    Ideas: is-white
  adsensePubId: 7398757278741889
  adsenseUnitId: 7456114770
  social:
    github: https://github.com/etrobot/hugo-theme-financlub
    twitter: https://twitter.com/etrobot